name: Use Custom Docker Action
on:
  push:
    branches:
      - main
jobs:
        run-custom-action:
          runs-on: ubuntu-latest
      
          steps:
            - name: set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.docker_username }}
                password: ${{ secrets.docker_hub_token }}
      
# pull the custom action from docker hub
            - name: Pull Docker Image
              run: docker pull giladalboher/nodejs

            - name: run the container
              run: docker run giladalboher/nodejs