name: Use Custom Docker Action
on:
  push:
    branches:
      - main
jobs:
        run-custom-action:
          runs-on: ubuntu-latest
      
          steps:
            - name: set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.docker_username }}
                password: ${{ secrets.docker_hub_token }}
#add a step that can only start after workflow A is completed the job
            - name: Wait for Workflow A completion
              run: echo "Waiting for Workflow A to complete..."

            - name: check workflow
              run: |
                echo "Workflow A status: ${{ github.event.workflow_run.conclusion }}"
                if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
                echo "Workflow A failed"
                exit 1
                fi


# pull the custom action from docker hub
            - name: pull and run
              run: |
                docker pull ${{ secrets.docker_username }}/custom-action:${{ github.sha }}
                docker run ${{ secrets.docker_username }}/custom-action:${{ github.sha }}
         